### ISSUE TITLE
Financier : Abandon de la ligne si Validation sans ventilations

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#18]
Lors de la création d’une nouvelle ligne d’extrait.  Suite à l’encodage du montant si on clique sur la touche <Validation> ou ALT-ENTER, le programme abandonne la ligne.

**Comment by BIAC-SCO** [comment]
@jgondon J'ai ajouté un message de confirmation pour demander si l'utilisateur est sûr de créer l'extrait si aucune ventilation n'est ajoutée. Est-ce le bon comportement à adopter ?

**Comment by jgondon** [comment]
@BIAC-SCO Oui cela me semble ok !
