### ISSUE TITLE
Recherche d'un compte général : navigation par flèches

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#20]
Lors de la recherche d’un compte général dans une contrepartie CTRL-F, les flèches ne fonctionnement pas.  Il est obligatoire d’utiliser la souris.

**Comment by BIAC-SCO** [comment]
@jgondon Impossible de reproduire le bug.

Scénario pour essayer de reproduire :
- Création d'une pièce comptable (Financier)
- Encoder un montant
- (+)
- Choix du type compte Général
- CTRL-F sur le champ autocomplete
- Navigation avec les flèches haut/bas

Mais chez moi, cela semble fonctionner correctement

**Comment by jgondon** [comment]
Je n'y arrive pas non plus. Tout semble fonctionner correctement
