### ISSUE TITLE
Maintenance fournisseur : Etat des lieux

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#22]
La maintenance fournisseurs a déjà été développée, cependant il semblerait qu'il reste des problèmes/mauvais fonctionnements.
Une première étape est donc de faire un état des lieux de la section puis de tester les user stories afin de trier ce qui est OK et ce qu'il reste à faire/améliorer.

**Comment by MHSana** [comment]
état des lieux fait le 16/04/2021
