### ISSUE TITLE
Maintenance fournisseur : listing des fournisseurs

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#23]
En tant qu'utilisateur, je souhaite voir la liste des fournisseurs enregistrés 

Scénario : 
- Lancement de l'app
- Navigation vers la page Maintenance/Fournisseurs
- Affichage du listing

Informations à afficher :
- Numéro
- Nom
- Matchcode
- Solde
- Adresse

**Comment by MHSana** [comment]
Les infos transmises pour les fournisseurs sont correctement affichées au niveau du front.
Néanmoins, Simon à précisé qu'il faudrait vérifier que les bonnes données soient récupérées pour le solde

**Comment by BIAC-SCO** [comment]
Des modifications vont devoir être apportées suite à #34 notamment au niveau du solde.
Sur les classes comptes BTR, une méthode GetSoldeComptable() existait, mais elle n'existe pas au niveau SQL.
Il faudra donc la rajouter au niveau du mapper pour pouvoir l'utiliser avec les données SQL.

`public decimal GetSoldeComptable()
	{
		return this.DebitAnneePrecedente + this.CreditAnneePrecedente + this.DebitAnnee + this.CreditAnnee + this.DebitPeriode + this.CreditPeriode;
	}`

**Comment by MHSana** [comment]
Méthode ajoutée au niveau du mapper.

Au niveau du filtre du listing, il a été modifié pour accepter plusieurs termes de recherches de champs différents.
Avant, rechercher "Clemency Rue longue 1" n'aurait pas retourné de résultat car "Clemency" fait partie d'une ligne d'adresse différente de "Rue longue".
Maintenant, la recherche retourne les résultats qui ont au moins une occurrence de chaque terme du filtre dans un champ ou plus.
