### ISSUE TITLE
Maintenance fournisseur : recherche dans le listing

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#24]
En tant qu'utilisateur, je souhaite pouvoir effectuer une recherche dans le listing afin de retrouver plus facilement un fournisseur.

Scénario : 
- Page maintenance/fournisseurs
- Dans le champ recherche, j'entre soit 
- - le numéro
- - le nom
- - le matchcode
- - l'adresse
- Le résultat de la recherche se base sur la règle contains des différents éléments
- La liste des fournisseurs s'actualise en retournant les résultats correspondant à la recherche

**Comment by BIAC-SCO** [comment]
Cette recherche va être à refaire suite à #34.
Il va ainsi falloir revoir cette fonctionnalité avec un endpoint sur l'API.

Points importants :
- L'adresse est composée de plusieurs champs différents
- La méthode Contains est valide pour les STRING, mais pas directement pour les INT
- Une entrée de recherche peut être valide pour plusieurs critères

**Comment by BIAC-SCO** [comment]
Erreur de ma part, la récupération des données se faisait déjà sur les données SQL et non pas les données BTR.
Le code est donc déjà fonctionnel, il y a juste une petite adaptation à effectuer ;
- Il y a une query sur le solde, qui n'est pas utile, et donc à supprimer
- La recherche sur l'adresse est à rajouter

**Comment by MHSana** [comment]
Le filtre ne prend plus en compte le solde.
Le filtre prend maintenant l'adresse en compte.
Le filtre a été modifié pour accepter plusieurs termes de recherches de champs différents.
Avant, rechercher "Clemency Rue longue 1" n'aurait pas retourné de résultat car "Clemency" fait partie d'une ligne d'adresse différente de "Rue longue".
Maintenant, la recherche retourne les résultats qui ont au moins une occurrence de chaque terme du filtre dans un champ ou plus.

**Comment by BIAC-SCO** [comment]
@jgondon Est-ce nécessaire de gérer le cas de l'adresse où on entre par exemple "Clemency rue longue 1", est-ce que les utilisateurs vont faire une recherche aussi poussée ou est-ce que simplement "Clemency" ça suffit ?

**Comment by jgondon** [comment]
@BIAC-SCO Clemency ca suffit. On verra a plus longue échéance si une recherche plus poussée est nécessaire. Il doit aussi pouvoir faire une recherche sur "longue"
