### ISSUE TITLE
Maintenance fournisseur : détails fournisseur

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#25]
En tant qu'utilisateur, je souhaite pouvoir voir les informations détaillées d'un fournisseur.

Scénario : 
- Page maintenance/fournisseurs
- Clic sur un fournisseur de la liste
- Ouverture d'une modal affichant les informations détaillées du fournisseur sélectionné

**Comment by MHSana** [comment]
Semble correcte, mais besoin de checker plus en avant la validité des données
