### ISSUE TITLE
Maintenance fournisseur : création d'un fournisseur

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#26]
En tant qu'utilisateur, je souhaite pouvoir créer un fournisseur.

Scénario :
- Page maintenance/fournisseurs
- Clic sur un bouton pour la création
- Ouverture d'une modal avec un formulaire permettant l'encodage des informations

**Comment by BIAC-SCO** [comment]
Informations fournisseur indiquées dans #35

**Comment by MHSana** [comment]
Pour l'instant, il est impossible d'ajouter un utilisateur.
L'API retourne une erreur 500 ainsi qu'un message d'erreur btrieve 46 (problème de lock des fichiers)

**Comment by MHSana** [comment]
La récupération des listes des codes représentants, famille et secteur était impossible (suite à l'upgrade de la dal du backend).
Les endpoints concernés ont étés modifiés.
Il reste cependant certains petits quirks à modifier.
Principalement, le nombre d'élément recherché peut être de valeur 0 (ou moins) dans la requête get (typiquement, si aucune valeur n'est indiquée et que la valeur par défaut est utilisée).
Pour l'instant, ne connaissant pas le comportement attendu dans ce genre de situation, j'ai hardcodé la modification des valeurs inférieures à 1 vers 100 (qui est la limite acceptée par les méthodes Search des dal du context). Néanmoins, ce bout de code risque de casser et doit donc être modifié.

**Comment by BIAC-SCO** [comment]
> 
> 
> Pour l'instant, il est impossible d'ajouter un utilisateur.
> L'API retourne une erreur 500 ainsi qu'un message d'erreur btrieve 46 (problème de lock des fichiers)

Pour ce point, une piste à explorer est l'état du locking de la DAL via le BTRContext. Pour ouvrir la DALComptesBTR par exemple, il faut appeller BTRContext.OpenComptesIO() pour changer le mode d'input du fichier en IO

**Comment by MHSana** [comment]
Dans le projet AcquaAccessCore, classe Btrieve.cs méthode Write( ).
Un appel à la méthode BTRCALL( ) est fait.
Le dernier argument de la liste, keynum, est hardcodé à -1. 
Néanmoins, la doc parle d'une valeur de [0 à 118]  (https://docs.actian.com/psql/psqlv13/index.html#page/btrieveapi%2Fbtrintro.htm%23ww3963).
Est-ce que l'erreur ne viendrait pas de ceci?

**Comment by MHSana** [comment]
Au niveau du formulaire du front, il y a plusieurs petits éléments qui peuvent/devraient être adressés.
**Dans la section Comptabilité**
Pas de validation pour le format des Iban/Bic et pas de feedback utilisateur si il entre une donnée erronée.
La donnée n'est pas non plus checkée au niveau du backend.
Le numéro de domiciliation doit être un nombre mais le front ne check pas la validité de la donnée.
**Dans la section Commercial**
Au niveau du front, la remise accepte des strings alors qu'elle ne devrait accepter que des number.
Une erreur est retournée par le backend qui ne peut pas faire la conversion mais il n'y a pas de feedback visuel direct comme pour les cases voisines.
L'auto complétion pour les code représentant, famille et secteur ne fonctionne plus.
Il est toujours possible de sélectionner un code via l'option de recherche (click sur l'icone de loupe), mais entrer manuellement la valeur ou la sélectionner dans la dropdown ne fonctionne pas.
**Dans la section Signalétique**
Pas de check du format pour les numéros de téléphone, fax, etc... (mais peut-être que c'est juste trop peu important que pour être implanté?)
**Option de sauvegarde**
Si la sauvegarde ne fonctionne, le front ne donne pas d'info complémentaires à l'utilisateur (en plus du message général disant qu'une erreur est survenue avec la possibilité de voir le numéro de l'erreur dans les détails). 
Par exemple, si je rentre un numéro de domiciliation qui n'est pas un number, je ne vais pas avoir de message m'indiquant que l'erreur provient de là.
Ce problème sera résolu quand les champs auront tous leurs validations mises à jour

**Comment by MHSana** [comment]
> changer le mode d'input du fichier en IO

C'était bien ça, l'insertion en DB fonctionne nickel, maintenant.

Bien qu'au niveau du front, on ne load pas les lignes qui viennent d'être ajoutées.
Faudrait-il le faire?

**Comment by BIAC-SCO** [comment]
Vérifier le rechargement des fournisseurs après la création pour avoir les données à jour dans le listing
