### ISSUE TITLE
Maintenance fournisseur : modification d'un fournisseur

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#27]
En tant qu'utilisateur, je souhaite pouvoir modifier un fournisseur encodé afin de mettre à jour/corriger des informations.

Scénario :
- Page maintenance/fournisseurs
- Sélection d'un fournisseur 
- Ouverture de la modal des informations
- Passage en mode édition au clic d'un bouton

**Comment by BIAC-SCO** [comment]
Informations fournisseur indiquées dans #35

**Comment by MHSana** [comment]
La tentative d'update d'un fournisseur retourne une erreur 500 ainsi qu'un message d'erreur depuis btrieve de code 46.
Il n'y a pas de feedback utilisateur en cas d'update infructueux.

**Comment by MHSana** [comment]
erreur 500 lors de l'upload corrigée (Voir issue 26 https://github.com/biac-log/acqua/issues/26).
Reste à regarder à la validation des données du model avant l'upload.
