### ISSUE TITLE
Maintenance fournisseur : modification du numéro de fournisseur

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#28]
En tant qu'utilisateur, je souhaite pouvoir éditer le numéro assigné à un fournisseur.

De base, un numéro est automatiquement assigné à un fournisseur lors de l'initialisation de la création (dernier n° fournisseur +1).
L'utilisateur va parfois vouloir le modifier afin de le définir lui-même.

Il faudra donc dans ce cas valider que le numéro est valide (pas encore utilisé, inclus dans le range) et le cas échéant notifier à l'utilisateur qu'il doit utiliser un numéro différent.

Scénario : 
- Page maintenance/fournisseurs
- Création d'un fournisseur
- Le numéro est initialisé par défaut et est en readonly
- Une icône permet de retirer le readonly si on clique dessus
- Si on modifie, valider le numéro

Même scénario lors de l'édition

**Comment by BIAC-SCO** [comment]
/!\ A vérifier s'il faut bien autoriser la modification lors de l'édition, et pas permettre uniquement lors de la création

**Comment by MHSana** [comment]
Lors de la création, l'utilisation d'un numéro déjà utilisé par un autre fournisseur fonctionne correctement.
Pour l'instant, lors d'un update, il est possible de modifier le numéro.
Si le comportement est voulu (voir commentaire précédent de Biac-sco), il faudra néanmoins y apporter une correction.
Pour l'instant, cliquer sur le champ mais ne pas apporter de modification entraine une erreur car le numéro est déjà utilisé (par lui-même). Il faudra penser à gérer ce cas particulier.

**Comment by BIAC-SCO** [comment]
@jgondon Est-ce que tu sauras vérifier l'info avec ton père ? Je n'ai pas réussi à retrouver de trace écrite parlant de cette partie ..

**Comment by jgondon** [comment]
@BIAC-SCO @MHSana Il n'est pas autorisé de modifier le numéro après la création d'un fournisseur
