### ISSUE TITLE
Maintenance fournisseur : Annulation de la création

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#29]
En tant qu'utilisateur, je souhaite pouvoir annuler la création de mon nouveau fournisseur afin de revenir au listing sans créer de nouveau fournisseur.

Scénario :
- Page maintenance/fournisseurs
- Création d'un nouveau fournisseur
- Encodage d'informations
- Clic sur le bouton d'annulation
- Remise à zéro du formulaire et fermeture de la modal

**Comment by MHSana** [comment]
Certains champs ne sont pas réinitialisés (not., dans la section comptabilité, les N° de compte associé, maître et vente/achat)

**Comment by MHSana** [comment]
Les derniers champs qui ne se réinitialisaient pas devraient maintenant correctement se réinitialiser à chaque fois.
