### ISSUE TITLE
Maintenance fournisseur : Annulation de l'édition

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#30]
En tant qu'utilisateur, je souhaite pouvoir annuler les modifications que j'ai apportées à un fournisseur afin de ne pas les enregistrer et ainsi garder l'état avant les modifications.

Il ne suffit pas ici de revenir à l'écran de listing, mais on veut plutôt réafficher le fournisseur dans l'état où il est enregistré en DB, sans les modifications qu'on a voulu lui apporter

Scénario : 
- Page maintenance/fournisseurs
- Sélection d'un fournisseur, ouverture de la modal des informations détaillées
- Passage en mode édition
- Modification d'informations
- Clic sur le bouton d'annulation
- Les données reviennent à leur état pré-modifications 
- On repasse en mode affichage et plus édition

**Comment by MHSana** [comment]
Les modifications n'étaient pas annulées quand l'update était annulé.
Corrigé sauf (oversight de ma part) pour certains champs qui posent aussi problème dans la création (section compta, n° de compte associé, maître et vente/achat

**Comment by MHSana** [comment]
Dernières modifications apportées. Tout devrait maintenant fonctionner comme prévu.
