### ISSUE TITLE
Maintenance fournisseurs : Amélioration de l'affichage du formulaire

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#31]
En tant qu'utilisateur, je souhaite pouvoir visualiser les informations détaillées d'un fournisseur de manière lisible et claire afin d'identifier rapidement l'information que je recherche et faciliter le processus d'encodage.

Le formulaire comprend beaucoup de champs, et pour l'instant on les affiche tous d'un coup, regroupés en "catégories".
Il faudrait repenser ce design pour pouvoir avoir un affichage plus dégagé.
Une piste pourrait être une séparation en onglets

**Comment by MHSana** [comment]
Mock avec l'utilisation de tabs Vuetify pour séparer les catégories
![PropositionFormFournisseur_TabsVuetify](https://user-images.githubusercontent.com/82578398/115401526-c84f6e00-a1ea-11eb-9a3f-12c6356fd7ee.png)

Mock avec l'utilisation d'un stepper Vuetify pour séparer les catégories
![PropositionFormFournisseur_StepperVuetify](https://user-images.githubusercontent.com/82578398/115401669-ef0da480-a1ea-11eb-8c41-f47361abb87a.png)

Mock avec l'utilisation d'expansion panel Vuetify pour séparer les catégories
![PropositionFormFournisseur_ExpansionPanelVuetify](https://user-images.githubusercontent.com/82578398/115403080-5d9f3200-a1ec-11eb-9cf1-cc77f71dc93d.png)

**Comment by BIAC-SCO** [comment]
@jgondon On voit ensemble pour définir lequel on utilise ?

**Comment by jgondon** [comment]
Vu ensemble, on part sur le premier (avec les tabs). Ajouter un entête. Review de l'ensemble entre @MHSana @Emlyawite @BIAC-SCO

**Comment by BIAC-SCO** [comment]
Remarques sur le mockup TABS :
- Retirer la property dense pour ravoir les inputs en taille normale (plus grande)
- Julien parlait de retirer le compteur de caractères, à voir si besoin une fois qu'on retire le dense
- Numéro et nom de fournisseur toujours visibles dans l'entête
- Codes représentants/familles/secteurs, un seul input comme AutocompleteComptes
- Onglets verticaux ?

**Comment by MHSana** [comment]
Quelques variations de la présentation par onglets

Avec la propriété "dense" toujours activée
![image](https://user-images.githubusercontent.com/82578398/115867425-6174c380-a43b-11eb-8285-a88d3da1a057.png)
half-screen
![image](https://user-images.githubusercontent.com/82578398/115867565-8d904480-a43b-11eb-8f29-3cef30043751.png)

Sans la propriété "dense"
![image](https://user-images.githubusercontent.com/82578398/115867716-b6183e80-a43b-11eb-85ed-57993f418ee7.png)
half-screen
![image](https://user-images.githubusercontent.com/82578398/115867760-c4665a80-a43b-11eb-9968-32e37872df60.png)

Sans bordure
![image](https://user-images.githubusercontent.com/82578398/115867871-e829a080-a43b-11eb-80d6-b2f9781b2ded.png)
Avec bordure
![image](https://user-images.githubusercontent.com/82578398/115867920-f5df2600-a43b-11eb-8253-03102c8dd8dc.png)

Feedback visuel pour l'utilisateur après l'envoi de la requête
![image](https://user-images.githubusercontent.com/82578398/115868051-22933d80-a43c-11eb-9ac3-e1a868ff1e5b.png)
half-screen
![image](https://user-images.githubusercontent.com/82578398/115868079-2c1ca580-a43c-11eb-8b0a-d3f9901bbb0b.png)

Onglets par dessus
![image](https://user-images.githubusercontent.com/82578398/115868437-bebd4480-a43c-11eb-8180-3014c48007f0.png)
Half-screen
![image](https://user-images.githubusercontent.com/82578398/115868473-c8df4300-a43c-11eb-8712-98639b3ec0cb.png)

J'ai les variations en local dans un fichier qui utilise un système de calque pour pouvoir rapidement visualiser l'une ou l'autre version.
Je peux le déposer ici si nécessaire.

**Comment by MHSana** [comment]
Pour gérer la validation partielle du formulaire, j'aurais aimé inclure ce genre de retour visuel
![image](https://user-images.githubusercontent.com/82578398/115871706-31302380-a441-11eb-8daf-ff8dd0cde851.png)

![image](https://user-images.githubusercontent.com/82578398/115871742-3c834f00-a441-11eb-9be5-c325863d6ea3.png)

**Comment by MHSana** [comment]
Voici l'avancée actuelle du formulaire : 
![image](https://user-images.githubusercontent.com/82578398/115903968-83cf0700-a464-11eb-8ebc-91482d528ec0.png)

Je me suis débattu un peu plus longtemps que ce que j'imaginais avec les messages d'erreurs.
J'ai créé un nouveau component AlertMessageSM en me basant sur le component AlertMessage déjà existant pour ne pas casser l'ui dans le reste de l'application.
J'ai maintenant une petite icône rouge au niveau de l'onglet quand un champs requis n'est pas complété.

Pour les codes assujetti et suivi, on avait parlé de mettre les termes complets plutôt que les diminutifs. Sauf erreur de ma part, les termes viennent de la DB et sont déjà écrits en raccourci. (Je revérifierais ça plus en avant lundi, mais je crois que c'est effectivement le cas). Si c'est effectivement le cas, je les mets en dur au niveau du front?

Pour l'option triangulaire, il n'y a pas moyen de fort agrandir la checkbox en restant dans les composants vuetify.
Je reste dans les composants vuetify au détriment de la taille de la checkbox ou est-ce qu'il est plus intéressant de refaire des checkbox maison? (La taille max de la checkbox via vuetify est la taille visible dans la screenshot de ce commentaire)

**Comment by jgondon** [comment]
Tres bien pour AlertMessageSM
Pour les codes suivi et assujetti, si les libelles viennent de la DB, il ne faut pas les modifier. On laisse comme cela.
Pour les checkboxs, on garde les composants vuetify.

**Comment by MHSana** [comment]
>Signalétique
Garder deux colonnes donnaient des résultats assez déplaisants
![image](https://user-images.githubusercontent.com/82578398/116099798-9fc4e980-a6ac-11eb-897b-72f0d1efdc1b.png)
![image](https://user-images.githubusercontent.com/82578398/116099901-b66b4080-a6ac-11eb-9e69-fc08a7e373c1.png)

J'ai donc remis les informations en une seule colonne.
Ce qui ne donne pas très bien en full width...
![image](https://user-images.githubusercontent.com/82578398/116100212-00ecbd00-a6ad-11eb-8f6f-b8f1dc9dbdf3.png)

Mais plutôt bien en réduisant la taille de la modale à 50% de la largeur (ou 100% de la largeur pour les plus petits écrans)
![image](https://user-images.githubusercontent.com/82578398/116100232-06e29e00-a6ad-11eb-8b63-1d267ac6de69.png)

Et les autres parties du formulaire donnent aussi assez bien en 50%
![image](https://user-images.githubusercontent.com/82578398/116100453-37c2d300-a6ad-11eb-98c6-9c1cca3c74d6.png)

**Comment by MHSana** [comment]
Résultat pour la signalétique
![image](https://user-images.githubusercontent.com/82578398/116109448-11089a80-a6b5-11eb-93ee-010a762002cf.png)

**Comment by MHSana** [comment]
Au niveau Commercial, j'ai réorganiser la grille pour qu'elle fonctionne avec un seul input.
Je n'ai par contre pas encore bien saisi comment gérer l'affichage code + nom dans le component
![image](https://user-images.githubusercontent.com/82578398/116121598-0eac3d80-a6c1-11eb-920b-ce0a67b6e594.png)

**Comment by MHSana** [comment]
Bug 
Quand on sélectionne un fournisseur pour avoir des détails, cliquer sur le code représentant/famille/secteur réinitialise la valeur.
Pourquoi ? ->onFocus, le component réinitialise la valeur affichée.
Résolution? -> Check si readonly == true.

**Comment by MHSana** [comment]
Formulaire full screen
![image](https://user-images.githubusercontent.com/82578398/116214191-c2a3dc00-a746-11eb-8312-9665b13fb259.png)
![image](https://user-images.githubusercontent.com/82578398/116214218-c9caea00-a746-11eb-9e57-2e4b60e5c0b6.png)
![image](https://user-images.githubusercontent.com/82578398/116214243-cf283480-a746-11eb-91e8-d20b8d7d197e.png)
![image](https://user-images.githubusercontent.com/82578398/116214272-d3ece880-a746-11eb-8fac-61e1e6bdb04f.png)

Formulaire demi-écran
![image](https://user-images.githubusercontent.com/82578398/116214398-f3841100-a746-11eb-9ca9-2f232527d49b.png)
![image](https://user-images.githubusercontent.com/82578398/116214426-fa128880-a746-11eb-8b89-638ea5b4684b.png)
![image](https://user-images.githubusercontent.com/82578398/116214452-01d22d00-a747-11eb-92e9-50693b1a8112.png)
![image](https://user-images.githubusercontent.com/82578398/116214524-131b3980-a747-11eb-83b9-0a2b65df321c.png)
![image](https://user-images.githubusercontent.com/82578398/116214670-3645e900-a747-11eb-941c-069653099162.png)

**Comment by jgondon** [comment]
@MHSana  Très bien ! Tu peux implémenter

**Comment by MHSana** [comment]
Par rapport au commit précédent (https://github.com/biac-log/acqua/commit/d9ecf8b90cf9e0308f6b58820499d1aab7ec31ca)
Ce à quoi correspondait le bug d'affichage readonly
![image](https://user-images.githubusercontent.com/82578398/116240733-72d40d80-a764-11eb-9a30-5df19f0b3cfc.png)
Ce à quoi cela ressemble maintenant
![image](https://user-images.githubusercontent.com/82578398/116240773-80899300-a764-11eb-96e0-b5aaf5a5ac70.png)
