### ISSUE TITLE
Opérations diverses : équilibre de la pièce

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#36]
(Mail feedback de Georges)
En changeant les dates des périodes, j’ai encodé une OD.
La pièce est équilibrée.  Le programme considère qu’elle est déséquilibrée !!!!!

@jgondon Possible d'avoir plus de détails ? J'ai fait un test en entrant des valeurs à l'équilibre et je n'ai pas le message, mais ton père a peut être entré des valeurs spécifiques qui concernent un cas particulier.

**Comment by jgondon** [comment]
Le problème venait d'une pièce qui est équilibré mais la couleur de 0 est rouge.
Normalement déjà corrigé.
