### ISSUE TITLE
Analyse Résultats Comptables

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#37]
Analyse business des résultats comptables (bilan et compte de résultats)

**Comment by BIAC-SCO** [comment]
@jgondon Analyse mise à jour avec les nouveaux détails.
Question optionnelle : Est-ce qu'on initialise les périodes par défaut en se basant sur les périodes comptables définies, ou est-ce qu'on laisse directement l'utilisateur rentrer les valeurs des périodes ?

**Comment by jgondon** [comment]
On met par défaut une comparaison entre période courante et période précédente. L'utilisateur aura la possibilité de changer les dates avant le chargement des données

**Comment by jgondon** [comment]
@BIAC-SCO J'ai revu l'analyse. Mes commentaires sont en gras/rouge ;)

**Comment by BIAC-SCO** [comment]
@jgondon Questions sur les commentaires :
- Tu parles d'une colonne par préfixe, on ne fait pas une seule colonne où on définit plusieurs préfixes séparés par une virgule ?
- D'ailleurs, en parlant de la virgule, le séparateur de colonne utilisé dans les CSV fournis est bien un point-virgule, la virgule est quant à elle utilisée dans les textes et pour séparer les préfixes c'est bien ça ?
- Dans le cas particulier du niveau parent qui définit le compte 20 (par exemple), il me semble que c'est ce que tu nous avais décrit non ? Le niveau supérieur qui définit un préfixe qui comprend les préfixes des niveaux enfants (j'ai rajouté un exemple)
- Pour le mockup, en effet je vais rajouter un bouton de chargement
- Pour l'option "bilan et/ou compte de résultats", je ne comprends pas bien, c'est juste au niveau du chargement des données alors ? Pas l'affichage ?
- Je vais mieux redéfinir les zones sur le mockup, mais on aura le sélecteur de structure, le sélecteur du mode d'affichage et le bouton de chargement dans une "entête de sélection" comme sur les autres pages, et le reste sera affiché une fois les données chargées. On n'a pas besoin d'avoir les inputs période affichés au début vu qu'on les initialise sur les périodes

**Comment by jgondon** [comment]
- Tous les éléments sont séparés par un ;
- Non, si il y a plusieurs préfixe, ils sont séparé par un ; nous avons donc une colonne par préfixe
- Un préfixe est toujours au plus bas niveau dans sa catégorie
- Pour l'ecran prévoir une zone d'encodage avec la structure, checkbox pour période 1 et 2 et date début et fin pour période, cehckbox si on veut le bilan, checkbox si on veut les PP et bouton de chargement. Une autre zone de visualisation des données
- Le et/ou c'est pour le chargement des données. Pour l'affichage c'est un OU
- Voir point précédent et si on a besoin des inputs même si elles sont initialisées
