### ISSUE TITLE
Migration en monorepo

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#38]
Passage des différents repos et services utilisés par AcQua dans un mode monorepo en vue de la migration vers Gitlab

**Comment by BIAC-SCO** [comment]
### Projets
- Acqua : Frontend VueJS
- ApiAcquaCore : Backend API

### APIs "Externes" utilisées
- ApiAcquaAuthenticationDB pour l'authentification utilisateur (sera remplacé par ApiAuthCore plus tard)
- ApiGestionUtilisateur pour la gestion des utilisateurs et leurs permissions (sera remplacé plus tard)
- ApiLogging pour le logging des exceptions
- ApiLocking

### Packages NuGet
- Tools-Acqua-Access-Core (1.0.10)
- ToolsCSharp (1.0.0)
- tools-logging (1.0.1)
- tools-webapi (1.0.1)

**Comment by BIAC-SCO** [comment]
## Proposition pour le monorepo

AcQua (repo)
|- apps (Contiendra les apps frontend)
|--- acqua (frontend Vue) 
|- services
|--- ApiAcquaCore (qui sera proablement découpé en modules)

Garder les APIs externes et les packages séparés

@jgondon Est-ce qu'ApiLocking est utilisée pour autre chose qu'Acqua ?

**Comment by jgondon** [comment]
@BIAC-SCO APILocking est actuellement utilisé que par AcQua et ne devrais pas être utilisé par autre chose

**Comment by BIAC-SCO** [comment]
@jgondon Ok, à intégrer à la partie services donc, merci

**Comment by BIAC-SCO** [comment]
Passage en structure monorepo effectuée, ainsi que la migration sur Gitlab. Nécessite encore l'ajout d'APILocking
