### ISSUE TITLE
Résultats Comptable : Sélection d'une structure d'affichage des données

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#39]
En tant qu'utilisateur, je souhaite pouvoir sélectionner la structure pour mes données dans une liste de structures que j'ai déjà définies afin de pouvoir facilement passer d'une structure à une autre.

Composant frontend  : sélecteur dropdown
Les données à afficher dans la liste devraient être renvoyées par l'API via le endpoint à créer dans #40

**Comment by MHSana** [comment]
@BIAC-SCO 
![AnalyseTechniqueIssue39](https://user-images.githubusercontent.com/82578398/116402931-43d59e80-a82d-11eb-8522-38a4bf392269.png)

**Comment by MHSana** [comment]
Après feed-bac de @BIAC-SCO 
![AnalyseTechniqueIssue39](https://user-images.githubusercontent.com/82578398/116435698-f0267d80-a84b-11eb-8390-523740d10655.png)
