### ISSUE TITLE
Résultats Comptable : Sélection de la période 1

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#41]
En tant qu'utilisateur, je souhaite pouvoir modifier les dates de la période sélectionnée afin de pouvoir voir mes résultats comptables pour un intervalle de temps différent.

Cette période sera initialisée par défaut sur les dates de la période actuelle. L'utilisateur pourra ensuite les modifier s'il souhaite.

Composant frontend : 2x DatePicker (composant custom d'AcQua)

**Comment by MHSana** [comment]
@BIAC-SCO La sélection de la date qui ne doit pas recharger automatiquement les données affichées à l'utilisateur, c'est bien cela?
Les données ne sont chargées que si et seulement si l'utilisateur utilise le bouton mentionné dans l'issue #44 ;?

**Comment by BIAC-SCO** [comment]
Je pense que c'est le plus judicieux oui, étant donné qu'il y a plusieurs paramètres différents que l'utilisateur peut modifier, cela pourrait faire trop de requêtes inutiles

**Comment by MHSana** [comment]
@BIAC-SCO 
![AnalyseTechniqueIssue41](https://user-images.githubusercontent.com/82578398/116406212-b6944900-a830-11eb-97c9-7b06b2c671c7.png)

**Comment by MHSana** [comment]
Après feed-back de @BIAC-SCO 
![AnalyseTechniqueIssue41](https://user-images.githubusercontent.com/82578398/116435852-18ae7780-a84c-11eb-8ec0-81cc7f15f84d.png)
