### ISSUE TITLE
Résultats Comptable : Sélection de la période 2

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#42]
En tant qu'utilisateur, je souhaite avoir la possibilité de définir une 2ème période si besoin afin de pouvoir avoir un affichage comparatif entre les 2 périodes.

Par défaut, cette période n'est pas définie. On aura à la place un bouton proposant de définir une deuxième période. En appuyant sur ce bouton, l'utilisateur aura accès à 2 inputs datepicker pour définir cette 2ème période comme pour la 1ère période. Cette 2ème période devrait être initialisée sur les dates de la période précédente. 
Lorsqu'on a les inputs pour définir cette nouvelle période, il faut prévoir un bouton pour "nullifier" cette période et retirer les inputs si l'utilisateur ne les veut plus.

Composants frontend :
Bouton "Ajouter une période"
2x inputs datepicker
Bouton "retirer"

**Comment by MHSana** [comment]
@BIAC-SCO 
![AnalyseTechniqueIssue42](https://user-images.githubusercontent.com/82578398/116407558-2ce57b00-a832-11eb-9f99-0bd8be447617.png)

**Comment by MHSana** [comment]
Après feed-back de @BIAC-SCO 
![AnalyseTechniqueIssue42](https://user-images.githubusercontent.com/82578398/116435878-206e1c00-a84c-11eb-8612-f20b8b025d59.png)
