### ISSUE TITLE
Résultats Comptable : Sélection des données à charger

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#43]
En tant qu'utilisateur, je souhaite avoir le choix de charger les données nécessaires pour calculer mon bilan et/ou mon compte de résultats afin de pouvoir charger ces données en une seule fois.

Les scénarios de choix possibles sont :
- Bilan
- Compte de résultats
- Bilan et compte de résultats

Il faut bien valider qu'au moins un des choix a été sélectionné. Selon les choix sélectionnés, certains affichages ne seront pas disponibles (ex. si l'utilisateur ne choisit de charger que les données bilan, on ne disposera pas des données pour l'affichage du compte de résultat)

Composants frontend : 2x checkboxes

**Comment by MHSana** [comment]
@BIAC-SCO 
![AnalyseTechniqueIssue43](https://user-images.githubusercontent.com/82578398/116412170-b39c5700-a836-11eb-8401-6db6267163ac.png)

**Comment by MHSana** [comment]
Après feed-back de @BIAC-SCO 
![AnalyseTechniqueIssue43](https://user-images.githubusercontent.com/82578398/116435750-02082080-a84c-11eb-9f30-f3666bb46eb7.png)
