### ISSUE TITLE
Résultats Comptable : Déclenchement du chargement des données

### ISSUE THREAD

**Issue by BIAC-SCO** [biac-log/acqua#44]
En tant qu'utilisateur, je souhaite pouvoir déclencher manuellement le chargement des données afin de ne pas effectuer les requêtes avant que j'aie défini les paramètres souhaités.

Pour cela, on rajoutera simplement un bouton qui déclenchera le chargement des données lorsque l'on clique dessus (ou au moyen d'un raccourci éventuellement).

Composant frontend : Bouton

**Comment by MHSana** [comment]
Après feed-back de @BIAC-SCO 
![AnalyseTechniqueIssue44](https://user-images.githubusercontent.com/82578398/116435773-07656b00-a84c-11eb-91b5-c25c5a8a2e58.png)
